version: '3.4'

services:
  fastapi:
    image: fastapi
    build:
      context: ./fastapi
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    networks:
      - personal

  thirdpartyemailpassword:
    image: thirdpartyemailpassword
    build:
      context: ./my-app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - personal
  
# rename network name
networks:
  personal:
    driver: bridge